language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  matrix:
   - DJANGO="Django>=1.11,<1.12

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - pip install "$DJANGO"
  - pip install python-coveralls
  - pip install coverage

script: "coverage run manage.py test"

after_success:
- coveralls
