language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  matrix:
   - DJANGO="Django>=1.11,<1.12
   - DJANGO="Django>=2"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - pip install "$DJANGO"
  - pip install python-coveralls
  - pip install coverage

before_script:
  - if [[ "$DJANGO" >= "2" ]]; then pip install django-markdown-app==0.9.4.1; fi

script: "coverage run manage.py test"

after_success:
- coveralls
